default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_user
  password: "004711"
  #socket: /var/run/mysqld/mysqld.sockd

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: pannier_production
  username: rails_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
